# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_auto_20160405_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaginasWeb',
            new_name='WebPageDB',
        ),
    ]
